hazard_model_ids = ["NSHM_v1.0.4"]
site_list = "NZ_0_1_NB_1_1"
vs30s = [
    150,
    175,
    200,
    225,
    250,
    275,
    300,
    350,
    375,
    400,
    450,
    500,
    525,
    600,
    750,
    900,
    1000,
    1500,
]
poes = [0.02, 0.025, 0.05, 0.1, 0.18, 0.22, 0.39, 0.4, 0.63, 0.86]
imts = [
    "PGA",
    "SA(0.1)",
    "SA(0.2)",
     "SA(0.3)",
     "SA(0.4)",
     "SA(0.5)",
     "SA(0.7)",
     "SA(1.0)",
     "SA(1.5)",
     "SA(2.0)",
     "SA(3.0)",
     "SA(4.0)",
     "SA(5.0)",
     "SA(6.0)",
     "SA(7.5)",
     "SA(10.0)"
]
aggs = ["mean", "0.05", "0.1", "0.2", "0.5", "0.8", "0.9", "0.95"]
