# cli command configuration example
hazard_model_ids = ["NSHM_v1.0.4"]
site_list = "NZ_0_1_NB_1_1"           #0.1 degree NZ grid ver 1
vs30s = [400]
imts = ["PGA"]
poes = [0.02, 0.1, 0.4, 0.86]
# aggs = ["0.5"]
aggs = ["mean", "0.05", "0.1", "0.2", "0.5", "0.8", "0.9", "0.95"]

